### PR TITLE
update index.js to address deprecation warning

### PR DESCRIPTION
**Pull request by mario-merino**

### CODE REVIEW

**Review by vkarpov15 — COMMENTED** [review]
LGTM from my perspective but I defer to @niftylettuce

**Comment by niftylettuce** [comment]
@vkarpov15 what version of Mongoose was `countDocuments` added?  we may need to do a `peerDependency` with that particular `>=` version.

Also I think we are missing this from docs on Mongoose with the `count` -> `countDocuments` deprecation:

> Note that if you migrate from `count` to `countDocuments` where are query operators including, but not limited to `$where`, `$near`, and `$nearSphere` that need replaced.  See <https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#countDocuments> for more information.

**Comment by vkarpov15** [comment]
@niftylettuce 5.2.0: https://github.com/Automattic/mongoose/blob/master/History.md#520--2018-07-02

See docs: https://mongoosejs.com/docs/deprecations.html#-count-

**Comment by paullbn** [comment]
Hi!
Will this PR be merged?

**Comment by niftylettuce** [comment]
@paullbn yes, just need a min

**Comment by niftylettuce** [comment]
Please use `mongoose-slug-plugin` newest version `2.0.0`:

```sh
npm install mongoose-slug-plugin@latest
```

Versions older than `v2.0.0` have the following deprecation message now upon installation:

"If you upgrade to v2.0.0+ please ensure you are using Mongoose v5.2+ or greater"

Any issues please let me know.

cc @paullbn

**Pull request closed without merging**
